#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum HelpTier {
    Core,
    Standard,
    Extra,
    Other,
}

#[derive(Clone, Copy, Debug)]
struct HelpMeta {
    tier: HelpTier,
    description: &'static str,
    order: usize,
}

const HELP_TIER_ORDER: &[HelpTier] = &[
    HelpTier::Core,
    HelpTier::Standard,
    HelpTier::Extra,
    HelpTier::Other,
];

const HELP_META: &[(&str, HelpTier, &str)] = &[
    ("a", HelpTier::Core, "Alias for attach — jump to a live or waking oracle without spelling the full verb."),
    ("attach", HelpTier::Core, "Smart attach to a live tmux session, or wake a fleet oracle before attaching."),
    ("ls", HelpTier::Core, "List live local sessions; use fleet for the persistent registry and discover for peers."),
    ("wake", HelpTier::Core, "Launch or reuse an oracle engine pane; use bring when you want it split into your current view."),
    ("work", HelpTier::Core, "Open or create a repo workspace, with optional issue/task context for the engine."),
    ("run", HelpTier::Core, "Type text into a target pane and press Enter; use send for raw text without submission."),
    ("send-enter", HelpTier::Core, "Press Enter in a target pane; pair with send when pending input needs manual submission."),
    ("send-key", HelpTier::Core, "Send one allowlisted tmux key to a target pane; use send-text for normal text input."),
    ("send-escape", HelpTier::Core, "Send Escape to a target pane for cancelling prompts or leaving terminal modes."),
    ("bg", HelpTier::Core, "Run a long command in detached tmux and sample it later without blocking this pane."),
    ("hey", HelpTier::Core, "Send a signed message to another oracle over federation; use messages to inspect the ledger."),
    ("kill", HelpTier::Core, "Immediately remove a tmux session, window, or pane; use done for worktree cleanup."),
    ("bud", HelpTier::Core, "Create a new oracle workspace from this one; use awaken for bud plus first trigger."),
    ("token", HelpTier::Core, "List and switch engine auth tokens; use codex/profile for adjacent account state."),
    ("bring", HelpTier::Core, "Bring an oracle here by planning a wake split into the current session."),
    ("b", HelpTier::Core, "Alias for bring — short path for pulling another oracle into your current session."),
    ("feed", HelpTier::Core, "Inspect local activity feed data, including active status and parse-line diagnostics."),
    ("x", HelpTier::Core, "Run a plugin from a source spec with optional sha256 pin verification."),
    ("plugin", HelpTier::Core, "Inspect and manage installed plugins; use x for one-shot source-spec execution."),
    ("update", HelpTier::Core, "Check or apply maw binary updates on the stable or alpha channel."),
    ("calver", HelpTier::Core, "Compute the next CalVer release version for stable or alpha release flows."),
    ("version", HelpTier::Core, "Show the build version for this maw binary."),
    ("send-text", HelpTier::Core, "Type text and press Enter into a target pane; use send when Enter must be separate."),
    ("sleep", HelpTier::Core, "Gracefully stop one oracle window; use kill for immediate removal or done for worktrees."),
    ("health", HelpTier::Core, "Check local and peer health surfaces before routing work across the fleet."),
    ("oracle", HelpTier::Core, "Inspect and manage oracle records; use ls for live panes and fleet for registry repair."),
    ("stop", HelpTier::Core, "Stop all fleet sessions; use sleep for one oracle or kill for immediate tmux removal."),
    ("done", HelpTier::Core, "Finish a worktree session, save retrospective state, kill the window, and remove the worktree."),
    ("finish", HelpTier::Core, "Alias for done — complete a worktree session rather than merely sleeping it."),
    ("take", HelpTier::Core, "Move a tmux window between oracle sessions; use pane/swap for pane-level movement."),
    ("squad", HelpTier::Core, "Lead-centric team workflow for start, join, say, and list without typing a team name."),
    ("awaken", HelpTier::Core, "Bud, wake, and fire the awakening ritual in one command."),
    ("send", HelpTier::Core, "Send raw text to a pane without pressing Enter; pair with send-enter to submit later."),
    ("init", HelpTier::Core, "Run first-time maw configuration setup for the local user."),
    ("pane", HelpTier::Core, "Work with panes in the current tmux window; use panes to list pane metadata."),
    ("swarm", HelpTier::Core, "Spawn multiple AI-agent panes side by side for collaborative work."),
    ("scaffold", HelpTier::Core, "Create an oracle repo skeleton without committing, waking, or awakening it."),
    ("awake", HelpTier::Core, "Launch an oracle process with an optional engine without firing the awaken trigger."),
    ("new", HelpTier::Core, "Create a plain tmux workspace session when you do not need oracle scaffolding."),
    ("preflight", HelpTier::Core, "Run readiness checks for version, plugins, dead agents, and config before a workflow."),
    // ===== #648 fanout: about-consent =====
    ("about", HelpTier::Standard, "Show oracle details — session, repo, windows, and fleet metadata; use ls for live status."),
    ("absorb", HelpTier::Extra, "Absorb one oracle into another, archive the donor, and switch to the receiver."),
    ("activity", HelpTier::Standard, "Classify pane activity by diffing peek snapshots; use feed for local activity events."),
    ("agent", HelpTier::Standard, "Alias for agents — list configured agent routes and live panes for one node or the fleet."),
    ("agents", HelpTier::Standard, "List configured agent routes and live panes; use agents gc to prune stale manifest entries."),
    ("alive", HelpTier::Standard, "Check whether a session or oracle is live and count panes; use ls for the full table."),
    ("archive", HelpTier::Extra, "Archive an oracle's tmux session and data."),
    ("artifact", HelpTier::Standard, "Alias for artifacts — list or fetch team task artifacts by team and task id."),
    ("artifacts", HelpTier::Standard, "List or fetch team task artifacts; use team status for active task state."),
    ("assign", HelpTier::Standard, "Fetch a GitHub issue and wake an oracle with its task prompt; use work for repo-first work."),
    ("attach-ssh", HelpTier::Extra, "Attach to a remote tmux session over SSH; use attach for local sessions."),
    ("audit", HelpTier::Extra, "Inspect native dispatch audit events with filters for anomalies, event name, time, or tail limit."),
    ("auth", HelpTier::Standard, "Sign and verify federation/auth payloads; use consent for human approval flows."),
    ("auto-pair-proof", HelpTier::Extra, "Build or verify auto-pair identity proofs for node/oracle trust bootstrapping."),
    ("auto-wake", HelpTier::Extra, "Plan whether a site should wake a target; use wake for direct oracle launch."),
    ("bind-host", HelpTier::Extra, "Explain how maw chooses a bind host from config, peer store, and local defaults."),
    ("break", HelpTier::Extra, "Break a pane out of the current window; use pane/take for higher-level movement."),
    ("buddy", HelpTier::Standard, "Alias for bud — create a new oracle workspace from this one."),
    ("capture", HelpTier::Standard, "Capture visible pane output or full scrollback; use peek for a quick latest-output glance."),
    ("census", HelpTier::Standard, "Render a fleet/node census snapshot; use agents or ls for live-pane detail."),
    ("channel", HelpTier::Standard, "Manage oracle channel plugins and repo/global channel config; wake auto-injects channels."),
    ("check", HelpTier::Standard, "Probe required and optional local tools such as bun, gh, ghq, git, tmux, uv, and uvx."),
    ("cleanup", HelpTier::Standard, "Clean zombie agent panes and prune stale Oracle registry entries."),
    ("codex", HelpTier::Extra, "Switch active per-account CODEX_HOME in .envrc; mirrors token use for Codex profiles."),
    ("commands", HelpTier::Standard, "Alias for help --all — show every registered command grouped by tier."),
    ("completions", HelpTier::Standard, "Generate shell completions and dynamic completion data for zsh, bash, fish, and scripts."),
    ("config", HelpTier::Standard, "Show, explain, and set maw configuration keys; use doctor for health checks."),
    ("consent", HelpTier::Standard, "List, approve, or reject pending consent requests; use consent-store for raw store views."),
    ("consent-approval", HelpTier::Extra, "Plan approve/reject consent outcomes with PIN verification and trust-entry creation."),
    ("consent-cleanup", HelpTier::Extra, "Delete a pending consent request from the store after validation."),
    ("consent-expiry", HelpTier::Extra, "Evaluate or expire a pending consent request at a given timestamp."),
    ("consent-pending-read", HelpTier::Extra, "Read one pending consent request by id without exposing the PIN."),
    ("consent-pending-status", HelpTier::Extra, "Update a pending consent request status to pending, approved, rejected, or expired."),
    ("consent-pin", HelpTier::Extra, "Hash or verify a normalized consent PIN; use consent-approval for approve/reject flows."),
    ("consent-request", HelpTier::Extra, "Create a pending peer consent request with summary, action, PIN, and expiry metadata."),
    ("consent-store", HelpTier::Extra, "Inspect or model trust and pending consent store entries; use consent for the human flow."),
    ("consent-trust-check", HelpTier::Extra, "Check whether a from:to:action consent trust tuple is currently approved."),
    ("discord", HelpTier::Standard, "Manage Discord fleet credentials, access, status, routing, and service lifecycle."),
    ("discord-inv", HelpTier::Extra, "Inspect a Discord bot's guild and channel inventory, with optional threads and JSON output."),
    ("discover", HelpTier::Standard, "List configured and discovered federation peers, inventory sources, and live tmux state."),
    ("doctor", HelpTier::Standard, "Diagnose maw installation health and repair supported configuration problems."),
    ("federation", HelpTier::Standard, "Inspect and synchronize multi-node federation state; use pair to add a peer."),
    ("federation-health", HelpTier::Extra, "Compare local and remote federation reachability, peer sets, latency, and clock health."),
    ("federation-identity", HelpTier::Extra, "Render the node URL and oracle ownership map advertised to federation peers."),
    ("federation-sync", HelpTier::Extra, "Plan or apply federation identity differences; use federation for the grouped workflow."),
    ("find", HelpTier::Standard, "Search agents, sessions, and fleet metadata for matching oracle context."),
    ("fleet", HelpTier::Standard, "Manage the persistent fleet registry; use ls for currently live sessions."),
    ("focus", HelpTier::Standard, "Focus a tmux pane by target or direction; use inspect to verify pane metadata."),
    ("forget", HelpTier::Extra, "Remove an oracle's local registry state with a dry-run preview before destructive cleanup."),
    ("gather", HelpTier::Standard, "Gather team member panes into the lead window; use scatter to separate them again."),
    ("handover", HelpTier::Standard, "Alias for take — move a tmux window from one oracle session to another."),
    ("help", HelpTier::Standard, "Show the curated command menu; add --all for the full tiered verb catalog."),
    ("inbox", HelpTier::Standard, "Read durable oracle messages and manage the cross-scope approval queue."),
    ("inspect", HelpTier::Standard, "Inspect pane metadata as text or JSON; use peek or capture for pane output."),
    ("join", HelpTier::Standard, "Join a source pane into a destination tmux window; use gather for whole teams."),
    ("learn", HelpTier::Standard, "Route codebase exploration to the oracle learning workflow, with fast or deep scope."),
    ("locate", HelpTier::Standard, "Locate an oracle's repo, session, fleet config, and federation node without side effects."),
    ("messages", HelpTier::Standard, "Query and operate the durable hey/message lifecycle ledger; use inbox for recipient work."),
    ("mv", HelpTier::Standard, "Renumber a tmux window within its session; use take to move it between sessions."),
    ("notify", HelpTier::Standard, "Persist a routine message to a recipient inbox without injecting text into its pane."),
    ("oracle-recruit", HelpTier::Extra, "Recruit an oracle into a squad through the consent-gated pairing flow."),
    ("oracle-skills", HelpTier::Extra, "Manage oracle skills across AI coding agents through arra-oracle-skills."),
    ("oracle-workon", HelpTier::Extra, "Spawn an oracle worktree team by composing wake task context, split, and swarm."),
    ("oracles", HelpTier::Standard, "Alias for oracle — list, scan, search, register, and inspect oracle records."),
    ("overview", HelpTier::Extra, "Open the paged tmux overview of fleet oracles; use ls for a compact live list."),
    ("pair", HelpTier::Standard, "Pair federation peers through an ephemeral-code handshake; use federation to inspect status."),
    ("panes", HelpTier::Standard, "List pane metadata; use pane swap to move panes or tile to arrange and spawn grids."),
    ("park", HelpTier::Standard, "Park a tmux tab for later restoration; use open when you only need to rejoin a hidden pane."),
    ("peek", HelpTier::Standard, "Peek at recent agent output without attaching; use capture when you need full scrollback."),
    ("peer", HelpTier::Standard, "Alias for peers — manage federation aliases, probe connectivity, and inspect remote nodes."),
    ("peers", HelpTier::Standard, "Manage federation peer aliases and probe remote nodes; use scout for liveliness discovery."),
    ("ping", HelpTier::Extra, "Ping all peer nodes or one named node to check connectivity and authentication status."),
    ("plugin-scaffold", HelpTier::Extra, "Validate plugin names and generate Rust or AssemblyScript manifest scaffolds; use plugin build afterward."),
    ("plugins", HelpTier::Standard, "Manage installed plugin sets and enablement; use plugin for lifecycle commands and x for one-shot execution."),
    ("policy", HelpTier::Extra, "Inspect plugin weight and default-activation policy; use plugins to change installed or enabled sets."),
    ("pr", HelpTier::Standard, "Open a pull request for the current work window, or inspect its existing PR metadata."),
    ("profile", HelpTier::Extra, "List, inspect, and switch named maw configuration profiles; use token for engine credentials."),
    ("project", HelpTier::Standard, "Learn, incubate, find, or list tracked repositories; use work when you are ready to open one."),
    ("reboot", HelpTier::Standard, "Alias for restart — update if requested, stop the fleet, then wake it again."),
    ("rename", HelpTier::Standard, "Rename a tmux tab by index or name; use rename-pane for a pane title."),
    ("rename-pane", HelpTier::Standard, "Rename a target pane title; use rename when changing a whole tmux tab."),
    ("reply", HelpTier::Standard, "Reply to a correlated request, or list pending replies for an oracle."),
    ("resize", HelpTier::Standard, "Resize the current pane by direction and amount, or equalize the window layout."),
    ("resolve", HelpTier::Extra, "Resolve a target against names, sessions, or worktrees without performing a mutation."),
    ("rest", HelpTier::Standard, "Stop all oracle fleet sessions for a full rest; use sleep for one oracle."),
    ("restart", HelpTier::Standard, "Restart the whole fleet, optionally updating to a selected git ref first."),
    ("resume", HelpTier::Standard, "Resume sleeping oracle fleet sessions; use wake when starting one specific oracle."),
    ("route", HelpTier::Extra, "Explain how a target routes across peers, agents, sessions, and windows without sending anything."),
    ("schedule", HelpTier::Extra, "Manage persistent per-oracle schedules, runs, logs, and pause or resume state."),
    ("scope", HelpTier::Standard, "List and manage access-control scopes and membership; use trust for pairwise authorization."),
    ("scout", HelpTier::Standard, "Discover peer liveliness through opt-in Scout or Zenoh transports; use peers to persist aliases."),
    ("serve", HelpTier::Standard, "Run or manage the maw HTTP and WebSocket server for APIs, federation, and browser views."),
    ("session", HelpTier::Standard, "Alias for whoami — print the current tmux session name."),
    ("setup", HelpTier::Standard, "Configure reboot-safe host services; use user-setup for per-user project configuration."),
    ("snapshots", HelpTier::Standard, "List, create, or inspect fleet recovery snapshots; use setup auto-wake to restore them after reboot."),
    ("split", HelpTier::Standard, "Split the current tmux pane and attach a target beside it; use bring to wake and split an oracle."),
    ("swap", HelpTier::Standard, "Swap two tmux panes by target; use pane for current-window pane operations."),
    ("t", HelpTier::Standard, "Alias for team — manage agent team lifecycle, tasks, messaging, and recovery."),
    ("tab", HelpTier::Standard, "List, create, rename, or close tmux windows; use session for the current session name."),
    ("tag", HelpTier::Standard, "Read or update maw metadata tags on a tmux target; use panes to inspect pane metadata."),
    ("talk", HelpTier::Standard, "Alias for talk-to — send a signed message through maw federation."),
    ("talk-to", HelpTier::Standard, "Send signed messages to another oracle or agent through maw federation."),
    ("talkto", HelpTier::Standard, "Alias for talk-to — send a signed message through maw federation."),
    ("team", HelpTier::Standard, "Manage agent team lifecycle, tasks, messaging, liveness, shutdown, and recovery."),
    ("tmux", HelpTier::Standard, "Use maw's guarded tmux controls for listing, peeking, splitting, attaching, and pane operations."),
    ("tokens", HelpTier::Extra, "List and switch engine credentials; use token for the primary token-management interface."),
    ("tonk", HelpTier::Extra, "Use Tonk oracle helpers for status, student-style greetings, and GitHub Discussions."),
    ("trust", HelpTier::Extra, "Manage pairwise sender-to-target trust used by scope access control."),
    ("trusts", HelpTier::Extra, "Alias for trust — list, pin, or revoke pairwise sender-to-target trust."),
    ("ui", HelpTier::Extra, "Install, launch, or tunnel the maw web UI; use --dev or --3d for development modes."),
    ("upgrade", HelpTier::Standard, "Alias for update — check or install a maw release from the stable or alpha channel."),
    ("user-setup", HelpTier::Standard, "Inspect or apply per-user maw project configuration; use setup for host boot services."),
    ("view", HelpTier::Standard, "Create or attach to an agent tmux view, optionally read-only or split beside this pane."),
    ("wave", HelpTier::Extra, "Coordinate a staged agent wave through start, status, dispatch, and teardown."),
    ("whoami", HelpTier::Standard, "Print the current tmux session, window, pane, and exact target."),
    ("workon", HelpTier::Standard, "Open or resume repository work with optional task, worktree, engine, and layout context."),
    ("workspace", HelpTier::Standard, "Create, join, share, and inspect multi-node workspaces; use workon for local repository work."),
    ("worktree", HelpTier::Standard, "List, add, or clean git worktrees; use done to finish an active worktree session."),
    ("xdg", HelpTier::Extra, "Inspect maw XDG paths and validate instance names; use setup for configuration changes."),
    ("zai", HelpTier::Standard, "Monitor, benchmark, and probe the configured Z.AI credential pool without printing tokens."),
    ("zoom", HelpTier::Standard, "Toggle tmux pane zoom for a target; use view when you need a separate attached view."),
];

fn help_meta_for(command: &str) -> HelpMeta {
    HELP_META
        .iter()
        .enumerate()
        .find_map(|(order, (name, tier, description))| {
            (*name == command).then_some(HelpMeta {
                tier: *tier,
                description,
                order,
            })
        })
        .unwrap_or(HelpMeta {
            tier: HelpTier::Other,
            description: "",
            order: usize::MAX,
        })
}

fn help_tier_label(tier: HelpTier) -> &'static str {
    match tier {
        HelpTier::Core => "core",
        HelpTier::Standard => "standard",
        HelpTier::Extra => "extra",
        HelpTier::Other => "other",
    }
}
